### ISSUE TITLE
Click on Track Order, navigate to tracking screen

### ISSUE THREAD

**Issue by ampslive** [ampslive/EasyLaundry#3]
When user, clicks on Track Order, navigate to tracking screen...

- [x] Input field for OrderId
- [x] Display Order Details
- [x] Display Order Status
- [x] Display Date of Completion

**Comment by Raphael-Evan** [comment]
![Screenshot 2023-10-05 081935](https://github.com/ampslive/EasyLaundry/assets/134363792/43ccd6dd-b0ad-432a-9b53-d0addec6d134)
![Screenshot 2023-10-05 081949](https://github.com/ampslive/EasyLaundry/assets/134363792/1c9c7aa5-1bc8-40c2-b767-997ead65e2c3)
